### PR TITLE
Properly move over DLLs

### PR DESCRIPTION
**Pull request by rylev**
This PR fixes an issue reported in #233 where dlls were not being properly moved over from the `nuget` directory to the debug and release directories. The issue was that we were looking for targets in the form of `win-$ARCH` instead of `win10-$ARCH`. 

Additionally this improves logging by adding a `--verbose` flag which can help with simply debugging.

### CODE REVIEW

**Comment by joekgh** [comment]
@rylev, I tested this branch and can confirm that it does sym link the Microsoft.UI.Xmal.dll into `target/debug`.  However for:
```
[package.metadata.winrt.dependencies]
"Microsoft.VCRTForwarders.140" = "1.0.6"
```
I now get an empty `target/nuget/Microsoft.VCRTForwarders.140` directory.

> writing dll file "win10-x64\\release\\vcruntime140_app.dll" into C:\Users\joe\workspace\win_ui\target\nuget\Microsoft.VCRTForwarders.140
           not creating symlink for win10-x64\release\vcruntime140_app.dll because of differing architecture to host architecture

I'm not sure what the intended behavior is in this case, but the version in master would download VCRTForwarders and extract the files to `target/nuget/Microsoft.VCRTForwarders.140`

One other nit.  "Fetching" is repeated:

> cargo winrt install
        Fetching: fetching Microsoft.UI.Xaml
        Fetching: fetching Microsoft.VCRTForwarders.140

**Comment by rylev** [comment]
@joekgh it seems that that nuget package differentiates between debug and release... I'll have to put in special logic for that.

**Comment by rylev** [comment]
@joekgh can you give this branch another try? I think it should work now when dlls are inside release directories.

**Comment by joekgh** [comment]
@rylev, it now works as expected.  Thanks.

**Pull request merged**
