### PR TITLE
Use squote for code generation

### PR DESCRIPTION
**Pull request by rylev**
This moves `winrt_gen` to using `squote`, a new crate I created which works just like `quote` except it simply stores things in a string instead of using the compiler backed TokenStream APIs. Since we're generating code from non-user input, this is a much more performant way to generate code. I'm hoping that this can be merged into [`quote` proper at some point](https://github.com/alexcrichton/proc-macro2/pull/239), but until then the squote crate is pretty minimal and easy to maintain. It's not yet on crates.io, but if we're happy with this direction, I can push it there.

A happy coincidence is now code generation is thread safe and so we can parallelize it. I used the [`rayon`](https://crates.io/crates/rayon) crate to simply make some of our iterators parallel, but perhaps we'll want to just do a simple thread pool instead so we don't take on an additional dependency. 

For my test crate which normally takes ~10 seconds to generate code (as its generating all of Windows.UI.Xaml), this change now generates code in 600ms. Without parallelization it generates code in about 2 seconds.

### CODE REVIEW

**Comment by kennykerr** [comment]
That's awesome - I originally created an elaborate coroutine scheduler for C++/WinRT but finally settled on a very simple threadpool-based task parallelizer that was just as fast and much simpler as it just used standard library primitives.

https://github.com/microsoft/cppwinrt/blob/master/cppwinrt/task_group.h

**Comment by rylev** [comment]
This is ready to go. For reference, on the stress test repo it takes 67 seconds to generate the token string in the `build!` macro using the current version of WinRT-rs. It now takes 8 seconds.

**Comment by rylev** [comment]
This also fixes #285

**Comment by simonbuchan** [comment]
I don't suppose you have memory comparison too? I would expect it to also be much better, of course.

**Comment by rylev** [comment]
I don't have a direct memory comparison as memory consumption is not a first order concern (given memory is typically not a bottleneck for compilation) though at some point I will do an analysis just to make sure we're being reasonable. I could see memory consumption being slightly worse as the proc_macro bridge does cache in local storage, but we'll have to see.

**Pull request merged**
